/* =============================================================================
 * idt.c — IDT construction, PIC remap, and interrupt dispatch.
 *
 * Responsibilities:
 *   1. Build a 256-entry Interrupt Descriptor Table.
 *   2. Install gate descriptors for vectors 0..47 that point at the asm
 *      stubs in isr_stubs.s (each stub pushes its vector number and jumps
 *      into the common handler, which calls `isr_handler` below).
 *   3. Remap the legacy 8259 PIC so IRQ 0..15 arrive on vectors 32..47
 *      (the default mapping overlaps CPU exceptions, which is a mess).
 *   4. Provide `isr_handler` — the single C function every ISR stub funnels
 *      into — and an IRQ registration API.
 *
 * What we deliberately don't do yet: nested interrupts (handlers run with
 * interrupts disabled by IF=0 on entry; we never re-enable them inside),
 * APIC (still on legacy 8259), SMP (single-CPU assumption everywhere).
 * ============================================================================= */

#include "idt.h"
#include "hal.h"
#include "printf.h"
#include "gdt.h"
#include "syscall.h"
#include "task.h"
#include <stdint.h>

/* --------------------------------------------------------------------------
 * Gate descriptor format (Intel SDM Vol 3, §6.11).
 *
 *   offset_low   — target EIP bits 15..0
 *   selector     — code segment selector to jump through (we use kernel CS)
 *   zero         — always 0
 *   type_attr    = | P | DPL(2) | 0 | D | 1 | 1 | 0 |
 *     P   = 1 : descriptor is present
 *     DPL = 0 : only ring 0 can invoke via int N  (we lower to 3 for a
 *               future syscall vector)
 *     D   = 1 : 32-bit gate (0 would be 16-bit)
 *     low 4 bits 0b1110 = 0xE : 32-bit Interrupt Gate
 *   offset_high  — target EIP bits 31..16
 *
 * 0x8E  = P=1, DPL=0, 32-bit Interrupt Gate (the common case).
 * -------------------------------------------------------------------------- */
struct idt_entry {
    uint16_t offset_low;
    uint16_t selector;
    uint8_t  zero;
    uint8_t  type_attr;
    uint16_t offset_high;
} __attribute__((packed));

/* Pointer structure for `lidt`: limit (2) + base (4). */
struct idt_ptr {
    uint16_t limit;
    uint32_t base;
} __attribute__((packed));

#define IDT_ENTRIES 256
static struct idt_entry idt[IDT_ENTRIES];
static struct idt_ptr   idtr;

/* C-callable handler table for the 16 PIC IRQs (vectors 32..47). */
static irq_handler_t irq_handlers[16] = { 0 };

/* --------------------------------------------------------------------------
 * asm stubs — declared so we can take their addresses in set_gate().  One
 * per vector, generated by the ISR_* macros in isr_stubs.s.
 * -------------------------------------------------------------------------- */
extern void isr0(void);  extern void isr1(void);  extern void isr2(void);  extern void isr3(void);
extern void isr4(void);  extern void isr5(void);  extern void isr6(void);  extern void isr7(void);
extern void isr8(void);  extern void isr9(void);  extern void isr10(void); extern void isr11(void);
extern void isr12(void); extern void isr13(void); extern void isr14(void); extern void isr15(void);
extern void isr16(void); extern void isr17(void); extern void isr18(void); extern void isr19(void);
extern void isr20(void); extern void isr21(void); extern void isr22(void); extern void isr23(void);
extern void isr24(void); extern void isr25(void); extern void isr26(void); extern void isr27(void);
extern void isr28(void); extern void isr29(void); extern void isr30(void); extern void isr31(void);
extern void isr32(void); extern void isr33(void); extern void isr34(void); extern void isr35(void);
extern void isr36(void); extern void isr37(void); extern void isr38(void); extern void isr39(void);
extern void isr40(void); extern void isr41(void); extern void isr42(void); extern void isr43(void);
extern void isr44(void); extern void isr45(void); extern void isr46(void); extern void isr47(void);
extern void isr128(void);                          /* int 0x80 — syscall */

static void (*const isr_table[48])(void) = {
    isr0,  isr1,  isr2,  isr3,  isr4,  isr5,  isr6,  isr7,
    isr8,  isr9,  isr10, isr11, isr12, isr13, isr14, isr15,
    isr16, isr17, isr18, isr19, isr20, isr21, isr22, isr23,
    isr24, isr25, isr26, isr27, isr28, isr29, isr30, isr31,
    isr32, isr33, isr34, isr35, isr36, isr37, isr38, isr39,
    isr40, isr41, isr42, isr43, isr44, isr45, isr46, isr47,
};

/* --------------------------------------------------------------------------
 * Minimal human-readable exception names, for panic logs.
 * -------------------------------------------------------------------------- */
static const char* const exception_name[32] = {
    "Divide Error", "Debug", "NMI", "Breakpoint",
    "Overflow", "BOUND Range", "Invalid Opcode", "Device Not Available",
    "Double Fault", "Coprocessor Segment Overrun", "Invalid TSS",
    "Segment Not Present", "Stack-Segment Fault", "General Protection",
    "Page Fault", "reserved", "x87 FP", "Alignment Check",
    "Machine Check", "SIMD FP", "Virtualization", "Control Protection",
    "reserved", "reserved", "reserved", "reserved",
    "reserved", "reserved", "reserved", "reserved", "reserved", "reserved",
};

/* --------------------------------------------------------------------------
 * PIC remap (8259A master + slave).
 *
 * Default mapping after BIOS init is:  master = vectors 0x08..0x0F,
 * slave = vectors 0x70..0x77.  The first range overlaps CPU exceptions
 * (e.g. IRQ0 timer == vector 8 == Double Fault) — unusable.  Remap to
 * 0x20..0x2F so IRQ N arrives as vector 32+N.
 *
 * Initialization sequence (per Intel 8259A datasheet, §ICW1..ICW4):
 *   ICW1: 0x11 — edge-triggered, cascade, expect ICW4
 *   ICW2: vector offset (master 0x20, slave 0x28)
 *   ICW3: master bit 2 = slave attached on IRQ2; slave = identity 2
 *   ICW4: 0x01 — 8086/88 mode (non-buffered, non-SFNM)
 *
 * Data port writes after ICW4 set the Interrupt Mask Register (IMR);
 * a 1 bit masks (disables) the corresponding line.  We start with every
 * line masked except the cascade on master IRQ2 — callers unmask specific
 * lines as they install handlers.
 * -------------------------------------------------------------------------- */
#define PIC1_CMD  0x20
#define PIC1_DATA 0x21
#define PIC2_CMD  0xA0
#define PIC2_DATA 0xA1
#define PIC_EOI   0x20

static void pic_remap(void) {
    outb(PIC1_CMD,  0x11);  outb(PIC2_CMD,  0x11);  /* ICW1 */
    outb(PIC1_DATA, 0x20);  outb(PIC2_DATA, 0x28);  /* ICW2 */
    outb(PIC1_DATA, 0x04);  outb(PIC2_DATA, 0x02);  /* ICW3 */
    outb(PIC1_DATA, 0x01);  outb(PIC2_DATA, 0x01);  /* ICW4 */

    /* Mask everything on both PICs; specific lines get unmasked as
     * handlers are installed.  Bit 2 on master is the cascade line to
     * the slave — leave it unmasked so slave IRQs can be delivered. */
    outb(PIC1_DATA, 0xFB);                  /* 1111 1011: unmask bit 2 */
    outb(PIC2_DATA, 0xFF);
}

/* Unmask a single IRQ line so the PIC will deliver it. */
static void pic_unmask(int irq) {
    uint16_t port = (irq < 8) ? PIC1_DATA : PIC2_DATA;
    uint8_t  mask = inb(port);
    mask &= ~(1 << (irq & 7));
    outb(port, mask);
}

/* Send End-Of-Interrupt so the PIC will deliver the next IRQ.  If the IRQ
 * came through the slave we must also EOI the slave; the master always
 * needs one. */
static void pic_eoi(int irq) {
    if (irq >= 8) outb(PIC2_CMD, PIC_EOI);
    outb(PIC1_CMD, PIC_EOI);
}

/* --------------------------------------------------------------------------
 * IDT construction.
 * -------------------------------------------------------------------------- */

static void set_gate(int vector, void (*handler)(void), uint8_t type_attr) {
    uintptr_t addr = (uintptr_t)handler;
    idt[vector].offset_low  = (uint16_t)(addr & 0xFFFF);
    idt[vector].selector    = GDT_KERNEL_CS;
    idt[vector].zero        = 0;
    idt[vector].type_attr   = type_attr;
    idt[vector].offset_high = (uint16_t)((addr >> 16) & 0xFFFF);
}

void idt_init(void) {
    /* Zero every entry so any vector we don't explicitly install is
     * marked not-present (P=0) — triggering a #NP we can debug, rather
     * than silently running a stale address. */
    for (int i = 0; i < IDT_ENTRIES; i++) {
        idt[i].offset_low  = 0;
        idt[i].selector    = 0;
        idt[i].zero        = 0;
        idt[i].type_attr   = 0;
        idt[i].offset_high = 0;
    }

    /* Install 48 gates: 32 exceptions + 16 IRQs.  0x8E = present,
     * ring 0, 32-bit interrupt gate. */
    for (int i = 0; i < 48; i++) set_gate(i, isr_table[i], 0x8E);

    /* Vector 0x80 (syscall): installed with DPL=3 so ring 3 can `int 0x80`
     * without the CPU raising #GP.  0xEE = P=1, DPL=3, 32-bit interrupt
     * gate. */
    set_gate(0x80, isr128, 0xEE);

    pic_remap();

    idtr.limit = sizeof(idt) - 1;
    idtr.base  = (uint32_t)(uintptr_t)&idt[0];
    __asm__ volatile ("lidt %0" : : "m"(idtr));

    kprintf("IDT: %d entries @ %p, PIC remapped to 0x20..0x2F\n",
            IDT_ENTRIES, (void*)idtr.base);
}

void irq_install(int irq, irq_handler_t handler) {
    if (irq < 0 || irq > 15) return;
    irq_handlers[irq] = handler;
    if (handler) pic_unmask(irq);
}

/* --------------------------------------------------------------------------
 * C-side dispatch.  Called from the common asm stub with a pointer to the
 * frame on the kernel stack.
 * -------------------------------------------------------------------------- */
void isr_handler(struct int_frame* f) {
    if (f->int_no < 32) {
        /* CPU exception.  Without a working fault recovery path, the only
         * safe move is to dump what we know and halt forever. */
        kprintf("\n!! EXCEPTION %d (%s) at cs:eip=%x:%p err=%x\n",
                f->int_no, exception_name[f->int_no],
                f->cs, (void*)f->eip, f->err_code);
        for (;;) __asm__ volatile ("cli; hlt");
    }

    if (f->int_no >= 32 && f->int_no < 48) {
        int irq = (int)f->int_no - 32;
        if (irq_handlers[irq]) irq_handlers[irq](f);
        pic_eoi(irq);
        /* Preemption point (M13): if the PIT (or any other handler) set
         * the deferred-reschedule flag, honor it now — AFTER the EOI so
         * the PIC will keep delivering ticks to whichever task we pivot
         * to.  schedule_check is a no-op when no reschedule is pending
         * or preempt_count > 0, so the cost on every IRQ is one branch. */
        schedule_check();
        return;
    }

    if (f->int_no == 0x80) {
        /* Syscall from ring 3 (or ring 0 — we don't restrict). */
        syscall_dispatch(f);
        return;
    }

    /* Any other vector (software interrupts) arriving at the default
     * handler is currently unexpected — log once and move on. */
    kprintf("unexpected vector %d at %p\n", f->int_no, (void*)f->eip);
}
