/* =============================================================================
 * idt.c — IDT construction, PIC remap, and interrupt dispatch.
 *
 * Responsibilities:
 *   1. Build a 256-entry Interrupt Descriptor Table.
 *   2. Install gate descriptors for vectors 0..47 that point at the asm
 *      stubs in isr_stubs.s (each stub pushes its vector number and jumps
 *      into the common handler, which calls `isr_handler` below).
 *   3. Remap the legacy 8259 PIC so IRQ 0..15 arrive on vectors 32..47
 *      (the default mapping overlaps CPU exceptions, which is a mess).
 *   4. Provide `isr_handler` — the single C function every ISR stub funnels
 *      into — and an IRQ registration API.
 *
 * What we deliberately don't do yet: nested interrupts (handlers run with
 * interrupts disabled by IF=0 on entry; we never re-enable them inside),
 * APIC (still on legacy 8259), SMP (single-CPU assumption everywhere).
 * ============================================================================= */

#include "idt.h"
#include "hal.h"
#include "printf.h"
#include "gdt.h"
#include "syscall.h"
#include "task.h"
#include "crash.h"      /* §M47 — record every fault */
#include "vmm.h"
#include "lapic.h"
#include "ioapic.h"
#include "pci.h"
#include "config.h"
#include "uaccess.h"   /* §1.1 — fault-fixup table for user copies */
#include <stdint.h>

/* --------------------------------------------------------------------------
 * Gate descriptor format (Intel SDM Vol 3, §6.11).
 *
 *   offset_low   — target EIP bits 15..0
 *   selector     — code segment selector to jump through (we use kernel CS)
 *   zero         — always 0
 *   type_attr    = | P | DPL(2) | 0 | D | 1 | 1 | 0 |
 *     P   = 1 : descriptor is present
 *     DPL = 0 : only ring 0 can invoke via int N  (we lower to 3 for a
 *               future syscall vector)
 *     D   = 1 : 32-bit gate (0 would be 16-bit)
 *     low 4 bits 0b1110 = 0xE : 32-bit Interrupt Gate
 *   offset_high  — target EIP bits 31..16
 *
 * 0x8E  = P=1, DPL=0, 32-bit Interrupt Gate (the common case).
 * -------------------------------------------------------------------------- */
struct idt_entry {
    uint16_t offset_low;
    uint16_t selector;
    uint8_t  zero;
    uint8_t  type_attr;
    uint16_t offset_high;
} __attribute__((packed));

/* Pointer structure for `lidt`: limit (2) + base (4). */
struct idt_ptr {
    uint16_t limit;
    uint32_t base;
} __attribute__((packed));

#define IDT_ENTRIES 256
static struct idt_entry idt[IDT_ENTRIES];
static struct idt_ptr   idtr;

/* C-callable handler table for the 16 PIC IRQs (vectors 32..47). */
static irq_handler_t irq_handlers[16] = { 0 };

/* APIC mode flag (M18).  Until M18 brings up LAPIC + IOAPIC, IRQs are
 * delivered via the 8259 PIC and EOIs go to it.  Once `idt_use_apic`
 * is called: route new IRQs through the IOAPIC and EOI via the LAPIC.
 * The IDT vector layout (IRQ N → vector 0x20+N) stays the same so the
 * isr_common stubs and handler table need no change. */
static int g_apic_mode = 0;
static uint8_t g_bsp_apic_id = 0;

/* --------------------------------------------------------------------------
 * asm stubs — declared so we can take their addresses in set_gate().  One
 * per vector, generated by the ISR_* macros in isr_stubs.s.
 * -------------------------------------------------------------------------- */
extern void isr0(void);  extern void isr1(void);  extern void isr2(void);  extern void isr3(void);
extern void isr4(void);  extern void isr5(void);  extern void isr6(void);  extern void isr7(void);
extern void isr8(void);  extern void isr9(void);  extern void isr10(void); extern void isr11(void);
extern void isr12(void); extern void isr13(void); extern void isr14(void); extern void isr15(void);
extern void isr16(void); extern void isr17(void); extern void isr18(void); extern void isr19(void);
extern void isr20(void); extern void isr21(void); extern void isr22(void); extern void isr23(void);
extern void isr24(void); extern void isr25(void); extern void isr26(void); extern void isr27(void);
extern void isr28(void); extern void isr29(void); extern void isr30(void); extern void isr31(void);
extern void isr32(void); extern void isr33(void); extern void isr34(void); extern void isr35(void);
extern void isr36(void); extern void isr37(void); extern void isr38(void); extern void isr39(void);
extern void isr40(void); extern void isr41(void); extern void isr42(void); extern void isr43(void);
extern void isr44(void); extern void isr45(void); extern void isr46(void); extern void isr47(void);
extern void isr64(void);                           /* LAPIC timer (M18.5) */
extern void isr65(void);                           /* reserved: cross-CPU preempt IPI */
extern void isr80(void);                           /* MSI pool (M18.6.5) */
extern void isr81(void);
extern void isr82(void);
extern void isr83(void);
extern void isr128(void);                          /* int 0x80 — syscall */

static void (*const isr_table[48])(void) = {
    isr0,  isr1,  isr2,  isr3,  isr4,  isr5,  isr6,  isr7,
    isr8,  isr9,  isr10, isr11, isr12, isr13, isr14, isr15,
    isr16, isr17, isr18, isr19, isr20, isr21, isr22, isr23,
    isr24, isr25, isr26, isr27, isr28, isr29, isr30, isr31,
    isr32, isr33, isr34, isr35, isr36, isr37, isr38, isr39,
    isr40, isr41, isr42, isr43, isr44, isr45, isr46, isr47,
};

/* --------------------------------------------------------------------------
 * Minimal human-readable exception names, for panic logs.
 * -------------------------------------------------------------------------- */
static const char* const exception_name[32] = {
    "Divide Error", "Debug", "NMI", "Breakpoint",
    "Overflow", "BOUND Range", "Invalid Opcode", "Device Not Available",
    "Double Fault", "Coprocessor Segment Overrun", "Invalid TSS",
    "Segment Not Present", "Stack-Segment Fault", "General Protection",
    "Page Fault", "reserved", "x87 FP", "Alignment Check",
    "Machine Check", "SIMD FP", "Virtualization", "Control Protection",
    "reserved", "reserved", "reserved", "reserved",
    "reserved", "reserved", "reserved", "reserved", "reserved", "reserved",
};

/* --------------------------------------------------------------------------
 * PIC remap (8259A master + slave).
 *
 * Default mapping after BIOS init is:  master = vectors 0x08..0x0F,
 * slave = vectors 0x70..0x77.  The first range overlaps CPU exceptions
 * (e.g. IRQ0 timer == vector 8 == Double Fault) — unusable.  Remap to
 * 0x20..0x2F so IRQ N arrives as vector 32+N.
 *
 * Initialization sequence (per Intel 8259A datasheet, §ICW1..ICW4):
 *   ICW1: 0x11 — edge-triggered, cascade, expect ICW4
 *   ICW2: vector offset (master 0x20, slave 0x28)
 *   ICW3: master bit 2 = slave attached on IRQ2; slave = identity 2
 *   ICW4: 0x01 — 8086/88 mode (non-buffered, non-SFNM)
 *
 * Data port writes after ICW4 set the Interrupt Mask Register (IMR);
 * a 1 bit masks (disables) the corresponding line.  We start with every
 * line masked except the cascade on master IRQ2 — callers unmask specific
 * lines as they install handlers.
 * -------------------------------------------------------------------------- */
#define PIC1_CMD  0x20
#define PIC1_DATA 0x21
#define PIC2_CMD  0xA0
#define PIC2_DATA 0xA1
#define PIC_EOI   0x20

static void pic_remap(void) {
    outb(PIC1_CMD,  0x11);  outb(PIC2_CMD,  0x11);  /* ICW1 */
    outb(PIC1_DATA, 0x20);  outb(PIC2_DATA, 0x28);  /* ICW2 */
    outb(PIC1_DATA, 0x04);  outb(PIC2_DATA, 0x02);  /* ICW3 */
    outb(PIC1_DATA, 0x01);  outb(PIC2_DATA, 0x01);  /* ICW4 */

    /* Mask everything on both PICs; specific lines get unmasked as
     * handlers are installed.  Bit 2 on master is the cascade line to
     * the slave — leave it unmasked so slave IRQs can be delivered. */
    outb(PIC1_DATA, 0xFB);                  /* 1111 1011: unmask bit 2 */
    outb(PIC2_DATA, 0xFF);
}

/* Unmask a single IRQ line so the PIC will deliver it. */
static void pic_unmask(int irq) {
    uint16_t port = (irq < 8) ? PIC1_DATA : PIC2_DATA;
    uint8_t  mask = inb(port);
    mask &= ~(1 << (irq & 7));
    outb(port, mask);
}

/* Send End-Of-Interrupt so the PIC will deliver the next IRQ.  If the IRQ
 * came through the slave we must also EOI the slave; the master always
 * needs one. */
static void pic_eoi(int irq) {
    if (irq >= 8) outb(PIC2_CMD, PIC_EOI);
    outb(PIC1_CMD, PIC_EOI);
}

/* --------------------------------------------------------------------------
 * IDT construction.
 * -------------------------------------------------------------------------- */

static void set_gate(int vector, void (*handler)(void), uint8_t type_attr) {
    uintptr_t addr = (uintptr_t)handler;
    idt[vector].offset_low  = (uint16_t)(addr & 0xFFFF);
    idt[vector].selector    = GDT_KERNEL_CS;
    idt[vector].zero        = 0;
    idt[vector].type_attr   = type_attr;
    idt[vector].offset_high = (uint16_t)((addr >> 16) & 0xFFFF);
}

void idt_init(void) {
    /* Zero every entry so any vector we don't explicitly install is
     * marked not-present (P=0) — triggering a #NP we can debug, rather
     * than silently running a stale address. */
    for (int i = 0; i < IDT_ENTRIES; i++) {
        idt[i].offset_low  = 0;
        idt[i].selector    = 0;
        idt[i].zero        = 0;
        idt[i].type_attr   = 0;
        idt[i].offset_high = 0;
    }

    /* Install 48 gates: 32 exceptions + 16 IRQs.  0x8E = present,
     * ring 0, 32-bit interrupt gate. */
    for (int i = 0; i < 48; i++) set_gate(i, isr_table[i], 0x8E);

    /* APIC vectors (M18.5).  0x40 is the per-CPU LAPIC timer tick;
     * 0x41 is reserved for a future cross-CPU preempt IPI.  DPL=0
     * (kernel-only). */
    set_gate(0x40, isr64, 0x8E);
    set_gate(0x41, isr65, 0x8E);

    /* MSI pool (M18.6.5).  4 vectors handed out by pci_alloc_msi.
     * EOI'd via lapic_eoi like other APIC vectors. */
    set_gate(0x50, isr80, 0x8E);
    set_gate(0x51, isr81, 0x8E);
    set_gate(0x52, isr82, 0x8E);
    set_gate(0x53, isr83, 0x8E);

    /* Vector 0x80 (syscall): installed with DPL=3 so ring 3 can `int 0x80`
     * without the CPU raising #GP.  0xEE = P=1, DPL=3, 32-bit interrupt
     * gate. */
    set_gate(0x80, isr128, 0xEE);

    pic_remap();

    idtr.limit = sizeof(idt) - 1;
    idtr.base  = (uint32_t)(uintptr_t)&idt[0];
    __asm__ volatile ("lidt %0" : : "m"(idtr));

    kprintf("IDT: %d entries @ %p, PIC remapped to 0x20..0x2F\n",
            IDT_ENTRIES, (void*)idtr.base);
}

/* APs call this to load the shared IDT on their own CPU.  IDTR is a
 * per-CPU register even though the table itself is one in memory —
 * each core needs its own lidt to start delivering interrupts. */
void idt_load(void) {
    __asm__ volatile ("lidt %0" : : "m"(idtr));
}

void irq_install(int irq, irq_handler_t handler) {
    if (irq < 0 || irq > 15) return;
    irq_handlers[irq] = handler;
    if (!handler) return;
    if (g_apic_mode) {
        /* Route via IOAPIC to BSP, vector = 0x20+irq.  ACPI ISO overrides
         * are honored inside ioapic_route_isa. */
        ioapic_route_isa(irq, (uint8_t)(0x20 + irq), g_bsp_apic_id);
    } else {
        pic_unmask(irq);
    }
}

/* ---------------------------------------------------------------------------
 * APIC mode switch (M18).  Called from kernel_main once acpi_init,
 * lapic_init_bsp, and ioapic_init have all succeeded.  Mask every
 * 8259 line and remember that future irq_install calls + EOIs route
 * through APIC instead.  Existing already-installed handlers
 * (typically PIT IRQ0 and PS/2 IRQ1) are re-routed via the IOAPIC
 * now that we know where to send them.
 * --------------------------------------------------------------------------- */
void idt_use_apic(uint8_t bsp_apic_id) {
    g_bsp_apic_id = bsp_apic_id;
    g_apic_mode   = 1;

    /* Re-route any IRQ that already has a handler — these were
     * installed under the 8259 path and want IOAPIC entries instead. */
    for (int irq = 0; irq < 16; irq++) {
        if (irq_handlers[irq]) {
            ioapic_route_isa(irq, (uint8_t)(0x20 + irq), bsp_apic_id);
        }
    }

    /* Mask every line on both 8259s — no more IRQ delivery from
     * legacy PIC.  Cascade (master IRQ2) included; we don't need it
     * once IOAPIC is the source. */
    outb(0x21, 0xFF);
    outb(0xA1, 0xFF);

    kprintf("apic: routing live (bsp_apic_id=%u), 8259 disabled\n",
            bsp_apic_id);
}

/* Map a CPU exception vector to the POSIX signal whose DEFAULT action is what
 * a faulting user process should get.  The exit code we terminate with is
 * 128+signal (the shell convention), so `ps` / the Task Manager show *why* a
 * package died.  SIGILL=4, SIGBUS=7, SIGFPE=8, SIGSEGV=11 (not all are in
 * syscall.h yet, hence the literals). */
static int fault_signal(int vec) {
    switch (vec) {
        case 0:  return 8;    /* #DE divide error        -> SIGFPE  */
        case 6:  return 4;    /* #UD invalid opcode      -> SIGILL  */
        case 13: return 11;   /* #GP general protection  -> SIGSEGV */
        case 14: return 11;   /* #PF page fault          -> SIGSEGV */
        case 16: return 8;    /* #MF x87 FPU error       -> SIGFPE  */
        case 19: return 8;    /* #XM SIMD FP error       -> SIGFPE  */
        default: return 11;   /* anything else           -> SIGSEGV */
    }
}

/* Lock-free hex writer to the serial port — usable from the NMI / fault paths
 * where taking the console lock could itself deadlock. */
static void ser_hex(uint32_t v) {
    extern void serial_write(const char* s);
    extern void serial_putchar(char c);
    serial_write("0x");
    for (int i = 7; i >= 0; i--) {
        int nyb = (int)((v >> (i * 4)) & 0xF);
        serial_putchar(nyb < 10 ? (char)('0' + nyb) : (char)('a' + nyb - 10));
    }
}

/* Ring-0 (kernel) fault policy — the user-configurable answer to "don't halt
 * the whole box just because one thing faulted".  `kernel.fault_policy`:
 *   halt   (default) — dump + stop this CPU forever (safest; state may be bad).
 *   reboot            — auto-restart the machine (panic=reboot style recovery).
 *   kill              — best-effort terminate just the faulting kernel thread
 *                       and keep running; if it was an M29-supervised service
 *                       the supervisor restarts it (that is the "auto-restart").
 *                       RISK: a kthread can hold a lock, so continuing may
 *                       deadlock — opt-in, off by default.
 * Never returns. */
static void ring0_fault_policy(int sig) __attribute__((noreturn));
static void ring0_fault_policy(int sig) {
    const char* pol = config_get("kernel.fault_policy", "halt");
    if (pol && (pol[0] == 'r' || pol[0] == 'R')) {
        kprintf("fault: kernel.fault_policy=reboot — restarting the machine\n");
        hal_reboot();                       /* if it returns, fall through to halt */
    } else if (pol && (pol[0] == 'k' || pol[0] == 'K')) {
        struct task* t = task_current();
        if (t && !t->is_idle && t->pid != 0) {
            kprintf("fault: kernel.fault_policy=kill — terminating kthread '%s' pid %d "
                    "(best-effort; may deadlock if it held a lock; M29 restarts a service)\n",
                    t->name, t->pid);
            task_exit_code(128 + sig);       /* noreturn: reschedules to another task */
        }
        kprintf("fault: kill policy — faulting context is idle/pid0, not killable; halting\n");
    }
    for (;;) __asm__ volatile ("cli; hlt");
}

/* --------------------------------------------------------------------------
 * C-side dispatch.  Called from the common asm stub with a pointer to the
 * frame on the kernel stack.
 * -------------------------------------------------------------------------- */
void isr_handler(struct int_frame* f) {
    /* §M31 L3 — NMI (vector 2) is our HARD-LOCKUP alarm: the ib700 hardware
     * watchdog fires it (via QEMU `-action watchdog=inject-nmi`) when the kernel
     * stops petting it — i.e. it's wedged spinning or hlt'ing with IRQs OFF, the
     * one failure the task-based watchdog layers can't see.  NMI is delivered
     * even with IRQs masked, so this handler runs in the frozen context.  Tiered
     * recovery (the user's choice): (1) LOG the stuck EIP/EFLAGS to the serial
     * port — lock-free, so it works in a deadlock — pinning the culprit; (2) try
     * to KILL the wedged task and re-enable IRQs on return so a halted CPU un-
     * sticks and the scheduler can reap it; (3) if the alarm keeps firing (the
     * kill/recover didn't take), REBOOT.  Do this before the generic exception
     * path, which would otherwise treat NMI as a fatal fault. */
    if (f->int_no == 2) {
        extern void serial_write(const char* s);
        extern volatile uint32_t g_nmi_lockups;
        g_nmi_lockups++;
        struct task* cur = task_current();
        /* §M47 — a hard lockup is precisely the failure the user would
         * otherwise experience as "it just froze": record it so the reason
         * survives the recovery (kill or reboot). */
        crash_report(CRASH_HARD_LOCKUP, cur ? cur->pid : -1,
                     cur ? cur->name : "?", (uintptr_t)f->eip, 0,
                     (int)((f->cs & 3) == 3),
                     ((f->cs & 3) == 3) ? "NMI lockup in ring 3"
                                        : "NMI lockup in the kernel");
        serial_write("\n!! NMI HARD-LOCKUP eip=");
        ser_hex(f->eip);
        serial_write(" cs="); ser_hex(f->cs);
        serial_write("\n");

        /* Decide recovery.  A lockup in RING 3 (a user task, cs low bits == 3)
         * holds no kernel locks, so force-killing it is safe and likely to work
         * → try that in place.  A lockup in RING 0 is a KERNEL deadlock: killing
         * the current kernel task can't be done safely (it may hold locks /
         * corrupt state), and re-enabling IRQs won't un-wedge a real deadlock —
         * so the only reliable recovery is a reboot.  Also reboot if a ring-3
         * attempt already failed once (g_nmi_lockups >= 2 — the counter is reset
         * to 0 by the watchdog task whenever the system is healthy). */
        int from_user = (f->cs & 3) == 3;
        if (!from_user || g_nmi_lockups >= 2) {
            serial_write("!! NMI HARD-LOCKUP: kernel-mode or persistent — rebooting\n");
            hal_reboot();
            for (;;) __asm__ volatile ("hlt");      /* if reboot is a no-op */
        }
        /* Ring-3 lockup, first alarm: flag the wedged task for force-kill (plain
         * writes, NMI-safe) + re-enable IRQs on iret so the scheduler runs and
         * reaps it at its next preemption; re-arm the watchdog so a failure
         * escalates to the reboot above. */
        if (cur && !cur->is_idle && cur->pid != 0) {
            cur->kill_forced  = 1;
            cur->kill_pending = 1;
        }
        f->eflags |= (1u << 9);                     /* set IF → iret enables IRQs */
        { extern void hw_watchdog_pet(void); hw_watchdog_pet(); }
        return;
    }

    if (f->int_no < 32) {
        /* M34 — copy-on-write page fault: a write to a fork-shared page.  Try
         * to resolve it (private copy) and retry; only if that declines is it a
         * real fault. */
        if (f->int_no == 14) {
            uint32_t cr2;
            __asm__ volatile ("mov %%cr2, %0" : "=r"(cr2));
            if (vmm_cow_fault(cr2)) return;
        }

        uint32_t _cr2 = 0;
        if (f->int_no == 14) __asm__ volatile ("mov %%cr2, %0" : "=r"(_cr2));

        /* §1.1 — user-access exception table.  If this KERNEL-mode fault came
         * from an instruction inside a uaccess primitive (a user pointer that
         * went bad DURING the copy — unmapped by another thread, a revoked COW
         * page — the window a pre-check can never close), resume at its fixup:
         * the copy returns -1 and the syscall reports -EFAULT.  Checked before
         * any fault policy, so this class can never halt the box. */
        if ((f->cs & 3) == 0) {
            uintptr_t pc = (uintptr_t)f->eip;
            if (uaccess_fixup_lookup(&pc)) { f->eip = (uint32_t)pc; return; }
        }

        /* §M46/M34 — a fault that happened in RING 3 (CS low 2 bits == 3) must
         * NEVER wedge the kernel.  This is the root cause of "a package froze
         * the whole system": previously ANY user fault fell through to the
         * cli;hlt below, killing the timer/IRQs on this CPU — so the cursor,
         * the scheduler AND the watchdog's own sweep timer all died with it.
         *
         * A user thread holds no kernel locks at a fault, so we can terminate
         * just that process here (its default fatal-signal action) and let the
         * scheduler pick someone else — exactly like the M46 force-kill safe
         * point, but triggered by a crash instead of a manual fkill.  The rest
         * of the system keeps running; init reaps the corpse and frees its
         * address space.  Only a ring-0 fault is genuinely unrecoverable. */
        if ((f->cs & 3) == 3 && task_current()) {
            struct task* t = task_current();
            int sig = fault_signal((int)f->int_no);
            kprintf("\nfault: user EXCEPTION %d (%s) pid %d '%s' "
                    "cs:eip=%x:%p err=%x cr2=%p — killing process\n",
                    f->int_no, exception_name[f->int_no], t->pid, t->name,
                    f->cs, (void*)f->eip, f->err_code, (void*)_cr2);
            /* §M47 — record it so the user can be told, now or later, by
             * whatever reporting sink happens to be armed. */
            crash_report(CRASH_USER_FAULT, t->pid, t->name,
                         (uintptr_t)f->eip, (uintptr_t)_cr2, sig,
                         exception_name[f->int_no]);
            task_exit_code(128 + sig);   /* noreturn: reschedules; reaper frees mm */
        }

        /* Ring-0 (kernel) exception.  Dump, then apply the configured policy
         * (halt / reboot / kill — see ring0_fault_policy). */
        kprintf("\n!! EXCEPTION %d (%s) at cs:eip=%x:%p err=%x cr2=%p\n",
                f->int_no, exception_name[f->int_no],
                f->cs, (void*)f->eip, f->err_code, (void*)_cr2);
        /* §M47 — capture BEFORE applying the policy: halt and reboot both mean
         * this function never returns, so a record written afterwards would
         * never exist.  On the reboot path the marker in NVRAM is what carries
         * the news across; on the halt path the record is in the ring for
         * whoever inspects the frozen guest. */
        {
            struct task* ct = task_current();
            crash_report(CRASH_KERNEL_FAULT, ct ? ct->pid : -1,
                         ct ? ct->name : "kernel",
                         (uintptr_t)f->eip, (uintptr_t)_cr2,
                         fault_signal((int)f->int_no), exception_name[f->int_no]);
        }
        ring0_fault_policy(fault_signal((int)f->int_no));
    }

    if (f->int_no >= 32 && f->int_no < 48) {
        int irq = (int)f->int_no - 32;
        if (irq_handlers[irq]) irq_handlers[irq](f);
        /* EOI: LAPIC for vectors delivered via IOAPIC, 8259 otherwise.
         * Switching at this single point keeps the rest of the handler
         * dispatch path arch-agnostic. */
        if (g_apic_mode) lapic_eoi();
        else             pic_eoi(irq);
        /* §M46 — force-kill safe point: if the interrupted task was in ring 3
         * (f->cs low 2 bits == 3) it holds no kernel locks, so a pending forced
         * kill can tear it down here (does not return for that task). */
        task_force_kill_point((f->cs & 3) == 3);
        /* Preemption point (M13): if the PIT (or any other handler) set
         * the deferred-reschedule flag, honor it now — AFTER the EOI so
         * the interrupt controller will keep delivering ticks to
         * whichever task we pivot to. */
        schedule_check();
        return;
    }

    /* LAPIC vectors (M18.5).  0x40 is the per-CPU preempt tick: each
     * CPU's LAPIC timer fires this independently of the PIT (which
     * only delivers to BSP).  We post a deferred reschedule the same
     * way pit_irq does so the standard schedule_check() at IRQ exit
     * honors it on the right core. */
    if (f->int_no == 0x40 || f->int_no == 0x41) {
        if (f->int_no == 0x40) schedule_request();
        lapic_eoi();
        task_force_kill_point((f->cs & 3) == 3);   /* §M46 — see IRQ block above */
        schedule_check();
        return;
    }

    /* MSI pool (M18.6.5).  Dispatch to driver handler installed via
     * pci_alloc_msi.  Handler must NOT block; runs with IRQs masked.
     * Same lapic_eoi + schedule_check as a LAPIC IRQ. */
    if (f->int_no >= 0x50 && f->int_no <= 0x53) {
        extern pci_msi_handler_fn pci_msi_handlers[4];
        unsigned idx = (unsigned)(f->int_no - 0x50);
        if (pci_msi_handlers[idx]) pci_msi_handlers[idx]();
        lapic_eoi();
        schedule_check();
        return;
    }

    if (f->int_no == 0x80) {
        /* Syscall from ring 3 (or ring 0 — we don't restrict). */
        syscall_dispatch(f);
        /* M34 — deliver a pending signal on the way back to ring 3 (rewrites
         * the trapframe to enter the handler; no-op in kernel mode). */
        signal_deliver(f);
        return;
    }

    /* Any other vector (software interrupts) arriving at the default
     * handler is currently unexpected — log once and move on. */
    kprintf("unexpected vector %d at %p\n", f->int_no, (void*)f->eip);
}
