#!/bin/sh
# =============================================================================
# fetch-musl-cross.sh — pin + clone musl-cross-make (§M38).
#
# musl-cross-make (richfelker) builds a from-source gcc/g++ + binutils + musl
# cross-toolchain that TARGETS musl — the clean way to get a musl libstdc++ +
# libgcc (with DWARF exception unwinding) for d-os.  We build it against the
# SAME musl version we vendor (MUSL_VER below == third_party/musl v1.2.5), so a
# C++ program's runtime and our provisioned /lib/ld-musl match exactly.
#
# The clone is gitignored (a build input, like third_party/musl); the built
# toolchain lands in third_party/musl-cross-<target>/ (also gitignored).
# Run this ON THE HOST once; then `make musl-cross-i686` builds in the container.
# =============================================================================
set -eu
cd "$(dirname "$0")/.."

MCM_DIR=third_party/musl-cross-make
MCM_URL=https://github.com/richfelker/musl-cross-make.git
MCM_REF=fe915821b652a7fa37b34a596f47d8e20bc72338   # master pin (2024)

if [ ! -d "$MCM_DIR/.git" ]; then
    echo "Cloning musl-cross-make into $MCM_DIR ..."
    git clone "$MCM_URL" "$MCM_DIR"
fi
git -C "$MCM_DIR" fetch --all --tags 2>/dev/null || true
git -C "$MCM_DIR" checkout "$MCM_REF" 2>/dev/null || \
    echo "note: could not pin $MCM_REF; using current checkout"

# config.mak — pin the musl version to our vendored one; TARGET is passed per
# build by the Makefile.  Skip docs (no makeinfo hassle).  Build C + C++.
cat > "$MCM_DIR/config.mak" <<'EOF'
# Generated by scripts/fetch-musl-cross.sh (§M38) — do not edit by hand.
# The pinned musl-cross-make (fe91582) ships hashes up to musl 1.2.3 and
# gcc 11.2.0.  musl 1.2.3 is ABI-compatible with our vendored 1.2.5 (both
# 1.2.x), so a C++ program built here runs fine on our /lib/ld-musl (1.2.5).
MUSL_VER = 1.2.3
GCC_VER = 11.2.0
# C and C++ only (no fortran/etc) — keeps the build lean.
LANGUAGES = c,c++
# Skip building/installing documentation.
MAKEINFO = true
EOF

# Patch: GNU tar >=1.30 (Ubuntu 22.04) fails to extract the sabotage
# linux-headers tarball with "Directory renamed before its status could be
# extracted" and exits non-zero.  --delay-directory-restore defers directory
# metadata restoration to the end and avoids it.  (TAR_OPTIONS doesn't reliably
# propagate through the sub-make recipe, so patch the extract rules directly.)
sed -i.bak -E 's/tar ([zjJ])xvf -/tar --delay-directory-restore -\1xvf -/' \
    "$MCM_DIR/Makefile" && rm -f "$MCM_DIR/Makefile.bak"

echo "musl-cross-make ready at $MCM_DIR (config.mak written, tar patched)."
echo "Next (in the container): make musl-cross-i686"
