#!/bin/sh
# =============================================================================
# fetch-wayland.sh — pin + clone UPSTREAM libwayland and libffi (§M40).
#
# §M26 built d-os's own Wayland SERVER plus a hand-written mini client library
# (user/libwl).  §M40 is the other half: run the REAL libwayland-client, so an
# unmodified Wayland application — eventually GTK/Qt/SDL — links against the
# same library it links against on Linux.
#
# Two pristine vendored dependencies (gitignored, never forked):
#
#   wayland — the client library itself.  Only a handful of C files matter
#             (wayland-client.c, connection.c, wayland-util.c, wayland-os.c)
#             plus the code wayland-scanner GENERATES from the protocol XML.
#             The scanner runs on the HOST (apt's wayland-scanner, see the
#             Dockerfile); nothing generated is committed.
#
#   libffi  — libwayland dispatches an incoming event by building an argument
#             list at runtime and calling the listener through ffi_call.  There
#             is no way around it short of forking the library, which is exactly
#             what this milestone exists NOT to do.
#
# Run ON THE HOST once; then build in the container with `make wayland`.
# =============================================================================
set -eu
cd "$(dirname "$0")/.."

clone() {   # clone <dir> <url> <ref>
    dir=$1; url=$2; ref=$3
    if [ ! -d "$dir/.git" ]; then
        echo "Cloning $(basename "$dir") into $dir ..."
        git clone --depth 1 --branch "$ref" "$url" "$dir"
    fi
    git -C "$dir" fetch --depth 1 origin "$ref" 2>/dev/null || true
    git -C "$dir" checkout "$ref" 2>/dev/null || echo "note: $dir using current checkout"
}

# 1.22.0 is the last release whose client library still builds with a plain
# C compiler invocation (no meson-only generated headers beyond the scanner's).
clone third_party/wayland https://gitlab.freedesktop.org/wayland/wayland.git 1.22.0

# Weston, for its reference clients.  `weston-simple-shm` is the canonical
# UNMODIFIED upstream Wayland application: libwayland + xdg-shell + wl_shm, no
# EGL, no GPU stack.  Running it is the honest proof that d-os is a Wayland
# compositor rather than a thing that talks to its own test client.  We build
# only clients/simple-shm.c + shared/os-compatibility.c; nothing is patched.
clone third_party/weston  https://gitlab.freedesktop.org/wayland/weston.git  13.0.0

# libffi comes as a RELEASE TARBALL, not a git clone: the git tree has no
# `configure` (it is generated by autogen.sh, which would drag autoconf +
# automake + libtool into the build image).  The release ships one, so the cross
# build is a plain ./configure --host=... and the image stays small.
FFI_VER=3.4.6
FFI_DIR=third_party/libffi
if [ ! -f "$FFI_DIR/configure" ]; then
    echo "Fetching libffi $FFI_VER ..."
    rm -rf "$FFI_DIR" /tmp/libffi-dl
    mkdir -p /tmp/libffi-dl
    curl -fsSL "https://github.com/libffi/libffi/releases/download/v$FFI_VER/libffi-$FFI_VER.tar.gz" \
        -o /tmp/libffi-dl/libffi.tar.gz
    tar -xzf /tmp/libffi-dl/libffi.tar.gz -C /tmp/libffi-dl
    mv "/tmp/libffi-dl/libffi-$FFI_VER" "$FFI_DIR"
    rm -rf /tmp/libffi-dl
fi

echo "Wayland + libffi ready."
echo "Next (in the container): make wayland            # i386"
echo "                          make ARCH=x86_64 wayland"
